# Generated by Django 2.2.6 on 2019-10-06 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('apikey', models.CharField(max_length=128)),
                ('owners', models.ManyToManyField(related_name='recordnames', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Zone')),
            ],
            options={
                'unique_together': {('name', 'zone')},
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rclass', models.CharField(max_length=2)),
                ('rtype', models.CharField(max_length=16)),
                ('rttl', models.PositiveIntegerField(default=300)),
                ('rdata', models.CharField(max_length=128)),
                ('rname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='records.RecordName')),
            ],
        ),
    ]
