# Generated by Django 2.2.7 on 2019-11-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='rdata',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='rname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='rttl',
            new_name='ttl',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='rtype',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='record',
            name='rclass',
        ),
    ]
