# Generated by Django 2.2.7 on 2019-11-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20191115_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA')], default='A', max_length=16),
        ),
    ]
