# Generated by Django 2.2.7 on 2019-11-17 21:13

from django.db import migrations, models
import records.models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20191117_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordname',
            name='apikey',
            field=models.CharField(default=records.models.generate_api_key, max_length=128),
        ),
    ]
