# Generated by Django 2.2.7 on 2019-11-20 20:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0004_auto_20191117_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordname',
            options={'verbose_name': 'Hostname', 'verbose_name_plural': 'Hostnames'},
        ),
        migrations.AddField(
            model_name='recordname',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='zone',
            name='owners',
            field=models.ManyToManyField(related_name='zones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recordname',
            name='name',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^([A-Za-z0-9\\_]|[A-Za-z0-9\\_][A-Za-z0-9\\_\\-]*[A-Za-z0-9])$', 'Names may not start or end with - and may only include alphanums and -.')]),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('name', 'type')},
        ),
    ]
