# Generated by Django 5.1.5 on 2025-01-31 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20191121_1255'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordname',
            name='owners',
            field=models.ManyToManyField(help_text='You will be added automatically on save.', related_name='recordnames', to=settings.AUTH_USER_MODEL),
        ),
    ]
